### ISSUE TITLE
Create complement file under the same-kind source folder

### ISSUE THREAD

**Issue by dmitrygusev** [anjlab/eclipse-tapestry5-plugin#25]
As suggested in #5

> For example if I want to create a tml file for a Java class in src/test/java it should default to creating the tml file in src/test/resources.

**Comment by trsvax** [comment]
I get this error when I try and update

An error occurred while collecting items to be installed
session context was:(profile=_Users_bfb_eclipse_jee-mars_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.anjlab.eclipse.e4.tapestry5,2.13.4
No repository found containing: osgi.bundle,com.anjlab.eclipse.tapestry5,2.13.4
No repository found containing: osgi.bundle,com.anjlab.eclipse.tapestry5.webtools,2.13.4
No repository found containing: org.eclipse.update.feature,com.anjlab.eclipse.e4.tapestry5.feature,2.13.4
No repository found containing: org.eclipse.update.feature,com.anjlab.eclipse.tapestry5.feature,2.13.4
No repository found containing: org.eclipse.update.feature,com.anjlab.eclipse.tapestry5.webtools.feature,2.13.4

**Comment by dmitrygusev** [comment]
@trsvax weird, try restarting eclipse?

Update went fine on my machine.

**Comment by trsvax** [comment]
I restarted and removed the old one and still get the error but the drag/drop installer works. I'll check it out today. Thanks
