### ISSUE TITLE
Error while trying to install the plugin in Spring Tool 4.10

### ISSUE THREAD

**Issue by prashant7526** [anjlab/eclipse-tapestry5-plugin#28]
While trying to install the plugin in Spring Tool 4.10, I am getting the following error:

Could not find: https://dl.bintray.com/anjlab/eclipse-tapestry5-plugin

**Comment by dmitrygusev** [comment]
Bintray has now been sunset, the plugin was only published there.

I'm afraid there's no other repository where this plugin is published, so you'll need to clone this repo and build your own release.

**Comment by prashant7526** [comment]
I have never did it before, I was confused how to do it. But thanks :)  I build it and it generated 3 jars files and I placed it in plugin. It is working like a charm. Thank you so much Dmitry at least for providing code. Please do not delete this repository. Thank for making me learn one more new thing
