### ISSUE TITLE
Update site not found

### ISSUE THREAD

**Issue by khalil00** [anjlab/eclipse-tapestry5-plugin#29]
Update site not found when added to Eclipse : [https://dl.bintray.com/anjlab/eclipse-tapestry5-plugin](https://dl.bintray.com/anjlab/eclipse-tapestry5-plugin) not working.

**Comment by dmitrygusev** [comment]
Please see https://github.com/anjlab/eclipse-tapestry5-plugin/issues/28

This project needs new home for binaries after Bintray sunrise.

I'll probably host it using gh-pages as per [this advice](https://twitter.com/waynebeaton/status/1400133729096503296) but don't have time right now, sorry.

**Comment by dmitrygusev** [comment]
Please check version 2.13.5 in releases:

https://github.com/anjlab/eclipse-tapestry5-plugin/releases

Until we find a better way of publishing we can use binary attachments in releases
